import gradio as gr
import ollama
import os
from docx import Document
from docx.shared import Inches, Pt
from docx.enum.text import WD_ALIGN_PARAGRAPH
import openpyxl
from openpyxl.chart import BarChart, Reference
from pptx import Presentation
from pptx.util import Inches as PptInches
import pandas as pd
from datetime import datetime

MODEL_INSTRUCT = 'qwen2.5:14b-instruct-q4_K_M'
MODEL_CODER = 'qwen2.5-coder:14b' # Buat Excel pake coder biar pinter rumus
OUTPUT_DIR = "hasil_output"
os.makedirs(OUTPUT_DIR, exist_ok=True)

def ollama_chat(prompt, model=MODEL_INSTRUCT):
    try:
        response = ollama.chat(model=model, messages=[{'role': 'user', 'content': prompt}])
        return response['message']['content']
    except Exception as e:
        return f"Error: {e}. Pastikan Ollama jalan & model udah di-pull."

def generate_docx(judul, isi_perintah):
    prompt = f"""
    Kamu adalah penulis laporan profesional. Buatkan isi laporan dengan judul: {judul}
    Perintah detail: {isi_perintah}

    Format:
    1. Gunakan struktur BAB I, BAB II, dst
    2. Kasih sub-bab yang relevan
    3. Panjang minimal 3 halaman. Bahasa Indonesia formal.
    4. Jangan pake markdown, tulis teks biasa.
    """
    isi_laporan = ollama_chat(prompt)

    doc = Document()
    # Cover
    doc.add_heading(judul, 0)
    doc.add_paragraph(f"Dibuat otomatis oleh aioffice - {datetime.now().strftime('%d %B %Y')}")
    doc.add_page_break()

    # Isi
    for paragraf in isi_laporan.split('\n'):
        if paragraf.strip().startswith('BAB'):
            doc.add_heading(paragraf, level=1)
        else:
            doc.add_paragraph(paragraf)

    filename = f"{OUTPUT_DIR}/Laporan_{judul.replace(' ', '_')}.docx"
    doc.save(filename)
    return filename, f"✅ Word berhasil dibuat: {filename}"

def generate_xlsx(perintah_data):
    prompt = f"""
    Kamu adalah data analyst. Buat data dummy + rumus Excel berdasarkan perintah: {perintah_data}
    Output HARUS format CSV saja, baris pertama adalah header. Jangan ada penjelasan lain.
    Contoh: Nama,NIM,UTS,UAS
    Budi,123,80,90
    """
    csv_data = ollama_chat(prompt, model=MODEL_CODER)

    # Simpan ke Excel
    filename = f"{OUTPUT_DIR}/Data_{datetime.now().strftime('%H%M%S')}.xlsx"
    try:
        from io import StringIO
        df = pd.read_csv(StringIO(csv_data))
        df.to_excel(filename, index=False)

        # Tambah grafik otomatis kalau ada kolom angka
        wb = openpyxl.load_workbook(filename)
        ws = wb.active
        if ws.max_column >= 2:
            chart = BarChart()
            data = Reference(ws, min_col=2, min_row=1, max_row=ws.max_row, max_col=ws.max_column)
            cats = Reference(ws, min_col=1, min_row=2, max_row=ws.max_row)
            chart.add_data(data, titles_from_data=True)
            chart.set_categories(cats)
            ws.add_chart(chart, "E2")
            wb.save(filename)

        return filename, f"✅ Excel berhasil dibuat: {filename}\nData:\n{df.head()}"
    except Exception as e:
        return None, f"Gagal buat Excel: {e}\nOutput AI:\n{csv_data}"

def generate_pptx(judul, outline_perintah):
    prompt = f"""
    Buat outline presentasi 10 slide untuk judul: {judul}
    Perintah: {outline_perintah}
    Format: Judul Slide | Poin 1 | Poin 2 | Poin 3
    Jangan pake markdown. Contoh:
    Pendahuluan | Latar Belakang Masalah | Rumusan Masalah | Tujuan
    """
    outline = ollama_chat(prompt)

    prs = Presentation()
    # Title slide
    title_slide = prs.slides.add_slide(prs.slide_layouts[0])
    title_slide.shapes.title.text = judul
    title_slide.placeholders[1].text = f"Generated by aioffice - {datetime.now().strftime('%d %B %Y')}"

    # Content slides
    for baris in outline.split('\n'):
        if '|' in baris:
            parts = [p.strip() for p in baris.split('|')]
            slide = prs.slides.add_slide(prs.slide_layouts[1])
            slide.shapes.title.text = parts[0]
            tf = slide.placeholders[1].text_frame
            for poin in parts[1:]:
                if poin: tf.add_paragraph().text = poin

    filename = f"{OUTPUT_DIR}/PPT_{judul.replace(' ', '_')}.pptx"
    prs.save(filename)
    return filename, f"✅ PPT berhasil dibuat: {filename}"

# GRADIO UI
with gr.Blocks(title="aioffice - AI Office Lokal", theme=gr.themes.Soft()) as app:
    gr.Markdown("# 🚀 aioffice - AI Office 100% Lokal")
    gr.Markdown("Bikin Word, Excel, PPT pake RTX 4060. Data aman di laptop sendiri.")

    with gr.Tab("📄 Generate Word"):
        judul_doc = gr.Textbox(label="Judul Laporan", placeholder="Contoh: Laporan Magang PT ABC")
        perintah_doc = gr.Textbox(label="Perintah Detail", lines=5, placeholder="Buatkan BAB I Pendahuluan, BAB II Tinjauan Pustaka, BAB III Pembahasan")
        btn_doc = gr.Button("Generate.docx", variant="primary")
        file_doc = gr.File(label="Download Word")
        info_doc = gr.Textbox(label="Status")
        btn_doc.click(generate_docx, [judul_doc, perintah_doc], [file_doc, info_doc])

    with gr.Tab("📊 Generate Excel"):
        perintah_xls = gr.Textbox(label="Perintah Data", lines=3, placeholder="Data 50 mahasiswa: Nama, NIM, UTS, UAS. Tambah kolom Nilai Akhir 40% UTS + 60% UAS")
        btn_xls = gr.Button("Generate.xlsx", variant="primary")
        file_xls = gr.File(label="Download Excel")
        info_xls = gr.Textbox(label="Status + Preview")
        btn_xls.click(generate_xlsx, [perintah_xls], [file_xls, info_xls])

    with gr.Tab("📽️ Generate PPT"):
        judul_ppt = gr.Textbox(label="Judul Presentasi", placeholder="Contoh: Sidang Skripsi Sistem Informasi")
        outline_ppt = gr.Textbox(label="Outline/Perintah", lines=3, placeholder="Buat 12 slide. Bahas latar belakang, metode, hasil, kesimpulan")
        btn_ppt = gr.Button("Generate.pptx", variant="primary")
        file_ppt = gr.File(label="Download PPT")
        info_ppt = gr.Textbox(label="Status")
        btn_ppt.click(generate_pptx, [judul_ppt, outline_ppt], [file_ppt, info_ppt])

if __name__ == "__main__":
    app.launch(inbrowser=True)